### ISSUE TITLE
Discuss creating a gh-pages training branch with Ivan

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/napmdtools#9]
@cassandrayuen 

Have a look at https://lucashertzog.github.io/gd/

I want to discuss making a branch on napmdtools that is similar and could get Anh to help next week, but want your feedback

**Comment by cassandrayuen** [comment]
I am migrating OSF NAPMD documentation to napmdtools github page, suggest a
separate DatSciTrain repo?

**Comment by cassandrayuen** [comment]
As seen here https://cardat.github.io/napmdtools/

**Comment by ivanhanigan** [comment]
excellent!
________________________________

**Comment by cassandrayuen** [comment]
Repos for training:
- General setup (install R, RStudio): https://github.com/cardat/DatSciTrain_set_up_R_and_friends
- NAPMD demo: https://github.com/cardat/DatSciTrain_napmd_api_demo
